DELETE FROM TB_BBS;
DELETE FROM TB_BEST;
DELETE FROM TB_BEST_DTL;
DELETE FROM TB_BSK;
DELETE FROM TB_BUY_DTL;
DELETE FROM TB_BUY_MST;
DELETE FROM TB_HP_SUR;
DELETE FROM TB_HP_SUR_DTL;
DELETE FROM TB_LIKE;
DELETE FROM TB_MBR_DTL;
DELETE FROM TB_MBR_MST;
DELETE FROM TB_MBR_ADDR;
DELETE FROM TB_MNG;
DELETE FROM TB_PAY;
DELETE FROM TB_RATE;
DELETE FROM TB_REVIEW;
DELETE FROM TB_REVIEW_IMG;
DELETE FROM TB_SLE;
DELETE FROM TB_SLE_IMG;
DELETE FROM TB_TRM_AGR;

COMMIT;

DROP SEQUENCE SQ_SEQ_BBS;
DROP SEQUENCE SQ_SEQ_BEST;
DROP SEQUENCE SQ_SEQ_BEST_DTL;
DROP SEQUENCE SQ_SEQ_BSK;
DROP SEQUENCE SQ_SEQ_BUY_DTL;
DROP SEQUENCE SQ_SEQ_BUY_MST;
DROP SEQUENCE SQ_SEQ_HP_SUR;
DROP SEQUENCE SQ_SEQ_HP_SUR_DTL;
DROP SEQUENCE SQ_SEQ_LIKE;
DROP SEQUENCE SQ_SEQ_MBR;
DROP SEQUENCE SQ_SEQ_MBR_ADDR;
DROP SEQUENCE SQ_SEQ_MNG;
DROP SEQUENCE SQ_SEQ_PAY;
DROP SEQUENCE SQ_SEQ_SLE;
DROP SEQUENCE SQ_SEQ_SLE_IMG;
DROP SEQUENCE SQ_SEQ_TRM_AGR;
DROP SEQUENCE SQ_SEQ_REVIEW;
DROP SEQUENCE SQ_SEQ_REVIEW_IMG;
DROP SEQUENCE SQ_SEQ_RATE;

COMMIT;

DROP TABLE TB_BBS;
DROP TABLE TB_BEST;
DROP TABLE TB_BEST_DTL;
DROP TABLE TB_BSK;
DROP TABLE TB_BUY_DTL;
DROP TABLE TB_BUY_MST;
DROP TABLE TB_HP_SUR;
DROP TABLE TB_HP_SUR_DTL;
DROP TABLE TB_LIKE;
DROP TABLE TB_MBR_ADDR;
DROP TABLE TB_MBR_DTL;
DROP TABLE TB_MBR_MST CASCADE CONSTRAINTS;
DROP TABLE TB_MNG;
DROP TABLE TB_PAY;
DROP TABLE TB_RATE;
DROP TABLE TB_REVIEW;
DROP TABLE TB_REVIEW_IMG;
DROP TABLE TB_SLE;
DROP TABLE TB_SLE_IMG;
DROP TABLE TB_TRM_AGR;

COMMIT;

DROP INDEX IDX_TB_MBR_LOGIN;
ALTER TABLE TB_MBR_MST DROP CONSTRAINT UK1_TB_MBR;

휴지통 비우기
purge recyclebin;